twilio: # Twilio gateway configuration
  accountId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  accountToken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  numbers:
    - +XXXXXXXXXXXXXX
    - #(620) 682-9903

  messagingServicesId: 
  localDomain: abc.xxx.com:4443

push:
  queueSize: 1000

#redphone:
  #authKey: # Deprecated

turn: # TURN server configuration
  secret: asasasas
  uris: ["xxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

cache: # Redis server configuration for cache cluster
  url: "redis://localhost:6379/1"
  replicaUrls: 
      - "redis://localhost:6379/2"
directory: # Redis server configuration for directory cluster
  url: "redis://localhost:6379/3"
  replicaUrls: 
      - "redis://localhost:6379/4"

messageCache:  
  redis: {url: "redis://localhost:6379/5", replicaUrls: ["redis://localhost:6379/6"]} 
  cacheRate: 1 
  persistDelayMinutes: 10 

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "admin@xxx"
  url: "jdbc:postgresql://127.0.0.1:5432/messagedb"

attachments: # AWS S3 configuration
  accessKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  accessSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  bucket: asasasasa

profiles: # AWS S3 configuration
  accessKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  accessSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  bucket: dfsdsdsd
  region: us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "admin@xxx"
  url: "jdbc:postgresql://127.0.0.1:5432/accountsdb"

#apn: # Apple Push Notifications configuration
  #bundleId:
  #pushCertificate:
  #pushKey:

gcm: # GCM Configuration
  senderId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  apiKey: AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
pushScheduler:                               
  url: "redis://localhost:6379/7"       
  replicaUrls: 
    - "redis://localhost:6379/8"
